[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "signal-storage"
description = "File-based signal storage"
dynamic = ["readme", "version"]
requires-python = ">=3.14"
dependencies = ["flask", "polars[pyarrow]", "pyarrow"]

[project.scripts]
signal-storage = "signal_storage:main"

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
readme = { file = ["README.md"] }
version = {attr = "signal_storage.__version__"}

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 120
target-version = "py314"
indent-width = 2
exclude = [
    "build",
    "docs",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    ".env",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "venv",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle - Error
    "W",   # pycodestyle - Warning
    "F",   # PyFlakes
    "C4",  # flake8 - Comprehensions
    "B",   # flake8 - Bugbear
    "I",   # Import sort
    "N",   # pep8 - Naming
    "PTH", # use pathlib
    "UP",  # PyUpgrade (new syntax)
]
ignore = ["N806"] # konstanty ve funkcích
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
packages = ["signal_storage"]
exclude = [
    "venv",
    ".venv",
    "build",
    ".env"
]
ignore_missing_imports = true
show_error_codes = true
warn_unused_ignores = true
warn_unused_configs = true
namespace_packages = true
explicit_package_bases = true
show_column_numbers = true
check_untyped_defs = true
disallow_untyped_defs = false
